title: Osimiri Alaezi
logo: osy.jpg

description:Data Analyst with experience using Microsoft excel for Report Automation,
Sql for data manipulation and interogation and Power bi for creating business insights. 
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal

